import { useMemo } from "react";
import type { UseFormReturn } from "react-hook-form";
import type { ProjectFormData } from "@/shared/schemas";
import { Label } from "@/app/_components/label";
import { Input } from "@/app/_components/input";
import { Textarea } from "@/app/_components/textarea";
import { LivePreviewCard } from "@/app/_components/live-preview-card";
import { SEO_CONFIG, AI_GOOD_EXAMPLE } from "@/shared/constants";
import { StepNavigation } from "./step-navigation";
import { AiFeedbackPanel } from "./ai-feedback-panel";

interface StepReviewProps {
  form: UseFormReturn<ProjectFormData>;
  isAutoDescription: boolean;
  setIsAutoDescription: (auto: boolean) => void;
  autoGeneratedDescription: string;
  primaryImageUrl: string | null;
  previews: string[];
  existingImages: string[];
  city: string;
  town: string;
  onPrev: () => void;
  isSubmitting: boolean;
  compressing: boolean;
  onGenerateAi: (details: string, feedback?: string) => void;
  isGeneratingAi: boolean;
  details: string;
}

export function StepReview({
  form,
  isAutoDescription,
  setIsAutoDescription,
  autoGeneratedDescription,
  primaryImageUrl,
  previews,
  existingImages,
  city,
  town,
  onPrev,
  isSubmitting,
  compressing,
  onGenerateAi,
  isGeneratingAi,
  details,
}: StepReviewProps) {
  const { register, watch, setValue } = form;
  const watchedTitle = watch("title") || "";
  const watchedDescription = watch("description") || "";
  const watchedBuildingType = watch("building_type") || null;
  const watchedCategories = watch("categories") || [];

  // SEO 게이지 계산
  const seoLengthStatus = useMemo(() => {
    const len = watchedDescription.length;
    if (len === 0) return { percent: 0, color: "bg-gray-250", label: "설명 작성 대기 중" };
    if (len < SEO_CONFIG.DESCRIPTION_MIN_LENGTH) {
      const pct = Math.min(100, Math.round((len / SEO_CONFIG.DESCRIPTION_MIN_LENGTH) * 75));
      return {
        percent: pct,
        color: "bg-amber-500 animate-pulse",
        label: `글자 수 조금 더 채우기 (최소 ${SEO_CONFIG.DESCRIPTION_MIN_LENGTH}자 권장)`,
      };
    }
    if (len <= SEO_CONFIG.DESCRIPTION_MAX_LENGTH) {
      return {
        percent: 100,
        color: "bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.4)]",
        label: "✓ 검색엔진(SEO) 검색 결과 최적 상태",
      };
    }
    return {
      percent: 100,
      color: "bg-rose-500",
      label: `글자 수 초과 (최대 ${SEO_CONFIG.DESCRIPTION_MAX_LENGTH}자 이하 권장)`,
    };
  }, [watchedDescription]);

  const displayRegion =
    city && town ? (city === "기타" ? town.trim() : `${city} ${town}`.trim()) : city;

  return (
    <section className="animate-fade-in space-y-5 rounded-3xl border border-gray-100 bg-white p-5 shadow-sm transition-all md:p-6 dark:border-gray-800 dark:bg-[#121824]">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-gray-50 pb-3 dark:border-gray-800">
        <div>
          <h2 className="text-navy flex items-center gap-2 text-lg font-bold dark:text-white">
            📝 5단계: 포트폴리오 최종 검토
          </h2>
          <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
            생성된 제목과 설명글을 최종 확인하고 다듬어 주세요.
          </p>
        </div>
        <button
          type="button"
          onClick={() => {
            const nextVal = !isAutoDescription;
            setIsAutoDescription(nextVal);
            if (nextVal) {
              setValue("description", autoGeneratedDescription);
            }
          }}
          className="rounded-lg border border-blue-200/50 bg-blue-50/10 px-2.5 py-1 text-xs font-bold text-blue-600 hover:underline dark:border-blue-900/30 dark:text-blue-400"
        >
          {isAutoDescription ? "⚙️ 직접 편집모드 전환" : "🔒 팩트 자동조립 전환"}
        </button>
      </div>

      <div className="space-y-4">
        {/* 노출용 제목 */}
        <div className="space-y-2">
          <Label htmlFor="title" className="text-sm font-semibold text-gray-700 dark:text-gray-200">
            포트폴리오 최종 제목
          </Label>
          <Input
            id="title"
            placeholder="제목을 입력하세요."
            {...register("title")}
            className="h-12 w-full rounded-xl border-gray-200 px-4 text-base transition-all focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 dark:border-gray-700"
          />
        </div>

        {/* 설명문 */}
        <div className="space-y-2">
          <Label
            htmlFor="description"
            className="text-sm font-semibold text-gray-700 dark:text-gray-200"
          >
            설명글 (SEO Meta Description)
          </Label>
          <Textarea
            id="description"
            {...register("description")}
            rows={6}
            placeholder="상세 설명글을 입력하거나 다듬어 주세요."
            readOnly={isAutoDescription}
            className={`w-full rounded-2xl px-4 py-3.5 text-base leading-relaxed transition-all focus:ring-4 focus:ring-blue-500/10 ${
              isAutoDescription
                ? "border-gray-150 cursor-not-allowed bg-gray-50/50 text-gray-600 opacity-90 dark:bg-gray-900/30 dark:text-gray-400"
                : "border-input bg-white text-gray-800 dark:bg-gray-900 dark:text-gray-100"
            }`}
          />
        </div>

        {/* 좋은 본문 작성 가이드 및 예시 박스 */}
        <div className="rounded-2xl border border-emerald-100 bg-emerald-50/15 p-4 text-xs leading-relaxed text-gray-600 transition-all dark:border-emerald-900/30 dark:bg-emerald-950/10 dark:text-gray-400">
          <div className="mb-1.5 flex items-center gap-1.5 font-bold text-emerald-800 dark:text-emerald-400">
            <span>🌟 권장하는 좋은 설명글 작성 예시</span>
          </div>
          <p className="mb-2.5 text-[11px] text-gray-500 dark:text-gray-400">
            자재의 일반 설명(예: '샤시는 추위를 막아줍니다')이나 주관적 느낌(예: '깔끔하고
            멋집니다')을 배제하고, <b>현장 위치, 명확한 자재 사양 및 시공 팩트</b> 중심으로 담백하게
            요약하여 작성 시 로컬 SEO 노출과 고객 신뢰도에 훨씬 효과적입니다.
          </p>
          <div className="rounded-xl border border-emerald-100 bg-white/80 p-3 font-mono text-[11px] text-emerald-800 italic shadow-sm dark:border-emerald-900/20 dark:bg-gray-950/60 dark:text-emerald-400">
            "{AI_GOOD_EXAMPLE.OUTPUT_WITHOUT_SIGNATURE}"
          </div>
        </div>

        {/* AI 수정 및 재생성 요청 패널 */}
        <AiFeedbackPanel
          initialDetails={details}
          onGenerateAi={onGenerateAi}
          isGeneratingAi={isGeneratingAi}
          compressing={compressing}
        />

        {/* SEO 적합도 게이지 */}
        <div className="dark:bg-gray-955/20 dark:border-gray-855 space-y-1.5 rounded-2xl border border-gray-100 bg-gray-50/50 p-3.5">
          <div className="flex items-center justify-between text-xs">
            <span className="font-bold text-gray-700 dark:text-gray-300">
              {seoLengthStatus.label}
            </span>
            <span className="text-gray-550 font-mono font-bold dark:text-gray-400">
              {watchedDescription.length}자
            </span>
          </div>

          <div className="dark:bg-gray-850 h-2 w-full overflow-hidden rounded-full bg-gray-200">
            <div
              className={`h-full rounded-full transition-all duration-300 ${seoLengthStatus.color}`}
              style={{ width: `${seoLengthStatus.percent}%` }}
            />
          </div>

          <div className="text-gray-450 dark:text-gray-555 pt-0.5 text-[10px] leading-relaxed">
            ※ 제목과 본문에 핵심 시공 정보가 골고루 담겨야 고객이 검색 시 높은 확률로 사이트가
            연결됩니다.
          </div>
        </div>

        {/* 실시간 시공사례 상세 미리보기 (Public View Mockup) */}
        <div className="space-y-3 border-t border-dashed border-gray-100 pt-4 dark:border-gray-800">
          <span className="block text-xs font-bold text-gray-700 dark:text-gray-300">
            📱 고객용 상세 페이지 실시간 미리보기 (Public View)
          </span>

          <LivePreviewCard
            title={watchedTitle}
            description={watchedDescription}
            images={[...existingImages, ...previews]}
            primaryImage={primaryImageUrl}
            categories={watchedCategories}
            region={displayRegion}
            buildingType={watchedBuildingType}
          />
        </div>
      </div>

      <StepNavigation
        onPrev={onPrev}
        nextType="submit"
        nextLabel="💾 시공사례 최종 저장"
        isSubmitting={isSubmitting}
        isNextDisabled={compressing}
      />
    </section>
  );
}
